### ISSUE TITLE
Proporsal: split webstorm-eap from webstorm-eap-jre

### ISSUE THREAD

**Issue by navarroaxel** [jthomaschewski/pkgbuilds#1]
Should we split `webstorm-eap-jre` from `webstorm-eap`?

It's implemented in several JetBrains AUR packages, e.g. [goland-jre](https://aur.archlinux.org/packages/goland-jre), [phpstorm-jre](https://aur.archlinux.org/packages/phpstorm-jre), [clion-jre](https://aur.archlinux.org/packages/clion-jre), [webstorm-jre](https://aur.archlinux.org/packages/webstorm-jre), etc.

I think is useful when the user of `webstorm-eap` wants to use any other `java-runtime`.

Also, I remember a bug in a specific JRE version built-in in a `WebStorm EAP` build officially released by JetBrains.

**Comment by jthomaschewski** [comment]
Sure, sounds useful. Feel free to add it if you like.
Thank you for maintaining this package, you where always much faster than me with updating so I was quite inactive since, sorry :)

How does `webstorm` determine which JRE to use?
Don't see any patching going on in the PKGBUILDs of the other AUR packages (which is good). So does WebStorm automatically fallback to the default JRE if the bundled is missing?

**Comment by navarroaxel** [comment]
With all JetBrains products happen the same, you install `webstorm` as the following:
```bash
$ aurman -S webstorm
```
(I use `aurman` but `yay` or whatever it's the same)

You should install the jre manually or the IDE doesn't open (It happened to me with `datagrip`):
```bash
$ aurman -S webstorm-jre
```

Or, all together:
```bash
$ aurman -S webstorm webstorm-jre
```

and for the remove:

```bash
$ aurman -Rns webstorm webstorm-jre
```

I have editing the PKGBUILD working with `webstorm-eap` and `webstorm-eap-jre`, and it's very similar to this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=webstorm

We can add a message during the `webstorm-eap` installation like teamviewer has: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=teamviewer

Maybe a warning with this pseudo code:

```
  if (webstorm-eap-jre is not installed)
    then (warning "webstorm-eap-jre" not installed, please install it or use a `java-runtime` of your election)
```

But I didn't see any JetBrains package with this `warning`. Maybe just an announce pinned in AUR is enough for now.

**Comment by navarroaxel** [comment]
I applied the change to `rubymine-eap`, looks working as expected. https://aur.archlinux.org/pkgbase/rubymine-eap/ (see the pinned comment).

I think is better to apply this change with a new `pkgrel` version. So the users will wonder why a patch to a version already working.

**Comment by jthomaschewski** [comment]
> You should install the jre manually or the IDE doesn't open (It happened to me with datagrip):

But whats the point in having the bundled JRE separate, if it can't be easily replaced with any other JRE?
I would have expected, that the IDE would fallback to the default IDE or something similar.

Will try your rubymine package 

UPDATE:
According to the dependencies it should automatically use the system jre if available, when bundled jre is not installed. If thats true and working, its fine with me:
```
  optdepends=('rubymine-eap-jre: JetBrains custom Java Runtime (Recommended)'
              'java-runtime: JRE - Required if rubymine-jre is not installed')
```

So *either* bundled jre *or* java-runtime (= any system-wide/global JRE) must be installed

**Comment by navarroaxel** [comment]
@jthomaschewski The IDE uses the `java-runtime` installed automatically, but the JBR is using v11 and I had openjdk v8 on my system. so I got an exception when I open the current JetBrains versions (`datagrip`, `rubymine`, etc).

I'm not sure which is the minimun version supported, but I think if the user wants to use a custom JRE, it's a user's responsibility.

Another option is when you install another JBR version, commonly installed in the user's home. That should work too. https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by navarroaxel** [comment]
@jthomaschewski I left you a PR branch with the edit for the `PKGBUILD`.
